apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gameplatform-pagamentos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gameplatform-pagamentos
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
