apiVersion: v1
kind: Service
metadata:
  name: gameplatform-pagamentos
spec:
  type: LoadBalancer
  selector:
    app: gameplatform-pagamentos
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
